export const SET_IS_WINDOW_FOCUSED = 'SET_IS_WINDOW_FOCUSED';
export const SET_APP_VIEW = 'SET_APP_VIEW';
export const SET_WINDOW_CONTEXT = 'SET_WINDOW_CONTEXT';
export const SET_IS_WINDOW_RESIZED = 'SET_IS_WINDOW_RESIZED';
