export const SUBSTRACT_HEALTH_POINTS = 'SUBSTRACT_HEALTH_POINTS';
export const SET_UNDERWATER_STAGE = 'SET_UNDERWATER_STAGE';
export const SET_IS_GAME_PAUSED = 'SET_IS_GAME_PAUSED';
export const RESET_GAME = 'RESET_GAME';
